ipvo/ipvo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('pub/', include('main.urls')),
    path('author/', include('main.urls')),
]

ipvo/main/urls.py
from django.urls import path
from . import views
from.views import *

app_name = 'main'

urlpatterns = [   
    path('publishers', PublisherList.as_view()),
    path('authors/', AuthorList.as_view()),
    path('pub/<publisher>', PublisherBookList.as_view()),
    path('author/<author>', AuthorBookList.as_view()),
    path('books/', BookList.as_view(), name="book_list"),
    path('add_book/', add_book, name='add_book'),
]

ipvo/main/models.py
from django.db import models

## Create your models here.


class Author(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    country = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    abstract = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    publication_date = models.DateField()

    def __str__(self):
        return self.title

ipvo/main/forms.py
from django import forms
from .models import *

class BookFilterForm(forms.Form):
    author = forms.ModelChoiceField(queryset=Author.objects.all(), required=False, empty_label="All Authors")
    publisher = forms.ModelChoiceField(queryset=Publisher.objects.all(), required=False, empty_label="All Publishers")
    
class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'abstract', 'author', 'publisher','publication_date']

ipvo/main/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.shortcuts import render, redirect
import datetime
from django.http import HttpResponse, HttpResponseNotFound
from .models import *
from django.views.generic import ListView
from .forms import BookFilterForm
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from .forms import BookForm


## Create your views here.

class BookList(ListView):
    model = Book
    
    emplate_name = 'main/book_list.html'
    context_object_name = 'book_list'

    def get_queryset(self):
        queryset = super().get_queryset()

        # Handle form submission
        form = BookFilterForm(self.request.GET)
        if form.is_valid():
            author = form.cleaned_data.get('author')
            publisher = form.cleaned_data.get('publisher')

            if author:
                queryset = queryset.filter(author=author)
            if publisher:
                queryset = queryset.filter(publisher=publisher)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = BookFilterForm(self.request.GET)
        return context

    
class AuthorList(ListView):
    model = Author


class PublisherList(ListView):
    model = Publisher

class PublisherBookList(ListView):
    template_name = 'main/book_list.html'

    def get_queryset(self):
        self.publisher = get_object_or_404(Publisher, name=self.kwargs['publisher'])
        return Book.objects.filter(publisher=self.publisher)

class AuthorBookList(ListView):
    template_name = 'main/book_list.html'

    def get_queryset(self):
        self.author = get_object_or_404(Author, name=self.kwargs['author'])
        return Book.objects.filter(author=self.author)
  
@csrf_exempt   
def add_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('../books')  # Redirect to the book list page
    else:
        form = BookForm()

    return render(request, 'main/add_book.html', {'form': form})

ipvo/main/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Knjižnica{% endblock %}</title>
</head>

<body>
    <h1>My library</h1>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/books">Books</a></li>
            <li><a href="/publishers">Publishers</a></li>
            <li><a href="/authors">Authors</a></li>
            <li><a href="/add_book">Add Book</a></li>
        </ul>
        {% endblock %}
    </div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

ipvo/main/templates/main/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Book</title>
</head>
<body>
    <h2>Add a New Book</h2>
    <form method="post" action="{% url 'main:add_book' %}">
        <!--{% csrf_token %}-->
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

ipvo/main/templates/main/author_list.html
{% extends "base_generic.html" %}
{% block content %}
<h2>Authors</h2>
{% for author in author_list %}
    <div class="author">
        <h4>{{author.name}}</h4>
        <p>City: {{author.city}}</p>
        <p>Country: {{author.country}}</p>
        <p><a href="../author/{{author.name}}"> All books by {{author.name}}</a></p>
    </div>
{% endfor %}
{% endblock %}

ipvo/main/templates/main/book_list.html
{% extends "base_generic.html" %}
{% block content %}
<h2>Books</h2>
<form action="{% url 'main:book_list' %}" method="get">
    <!--{% csrf_token %}-->
        {{ form.as_p }}
        <button type="submit">Filter</button>
    </form>
{% for book in book_list %}
    <div class="book">
        <h4>{{ book.title }}</h4>
        <p>Author: <a href="../author/{{book.author}}"> {{book.author}}</a></p>
        <p>{{ book.abstract }}</p>
        <p>Published by: <a href="../pub/{{book.publisher}}"> {{ book.publisher}}</a></p>
    </div>
{% endfor %}
{% endblock %}

ipvo/main/templates/main/publisher_list.html
{% extends "base_generic.html" %}
{% block content %}
    <h2>Publishers</h2>
    <ul>
        {% for publisher in publisher_list %}
            <li>
                Name: {{ publisher.name }}<br>
                City: {{ publisher.city }}<br>
                <a href="../pub/{{publisher.name}}"> All books by {{publisher.name}}</a></p>
            </li>
            <br>
        {% endfor %}
    </ul>
{% endblock %}